<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            // 3 bản ghi đã có
            [
                'category_id' => 1,
                'name' => 'Smartphone',
                'description' => 'Latest model smartphone with advanced features',
                'price' => 699.99,
                'discount' => 10,
                'quantity' => 50,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Laptop',
                'description' => 'High-performance laptop for professionals',
                'price' => 1199.99,
                'discount' => 15,
                'quantity' => 30,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Headphones',
                'description' => 'Noise-cancelling over-ear headphones',
                'price' => 199.99,
                'discount' => 5,
                'quantity' => 100,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            // 20 bản ghi mới
            [
                'category_id' => 3,
                'name' => 'Smart Watch',
                'description' => 'Track your fitness with this advanced smart watch',
                'price' => 149.99,
                'discount' => 10,
                'quantity' => 200,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Tablet',
                'description' => 'Portable tablet for work and entertainment',
                'price' => 299.99,
                'discount' => 5,
                'quantity' => 150,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Bluetooth Speaker',
                'description' => 'Portable wireless Bluetooth speaker',
                'price' => 49.99,
                'discount' => 15,
                'quantity' => 120,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Digital Camera',
                'description' => 'High-definition digital camera for photography enthusiasts',
                'price' => 499.99,
                'discount' => 20,
                'quantity' => 75,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Air Conditioner',
                'description' => 'Energy-efficient air conditioner for home use',
                'price' => 799.99,
                'discount' => 10,
                'quantity' => 60,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Gaming Console',
                'description' => 'Latest gaming console for next-level gaming experience',
                'price' => 399.99,
                'discount' => 25,
                'quantity' => 200,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Wireless Keyboard',
                'description' => 'Ergonomic wireless keyboard for comfortable typing',
                'price' => 79.99,
                'discount' => 5,
                'quantity' => 500,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Smart Thermostat',
                'description' => 'Smart thermostat to control your home temperature',
                'price' => 129.99,
                'discount' => 15,
                'quantity' => 80,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Laptop Stand',
                'description' => 'Adjustable stand for laptops and notebooks',
                'price' => 29.99,
                'discount' => 10,
                'quantity' => 150,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Smartphone Case',
                'description' => 'Protective case for smartphones',
                'price' => 19.99,
                'discount' => 0,
                'quantity' => 300,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Refrigerator',
                'description' => 'Energy-efficient refrigerator with smart features',
                'price' => 899.99,
                'discount' => 10,
                'quantity' => 40,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Monitor',
                'description' => 'High-resolution monitor for work and gaming',
                'price' => 199.99,
                'discount' => 10,
                'quantity' => 250,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Projector',
                'description' => 'Portable projector for presentations and entertainment',
                'price' => 349.99,
                'discount' => 5,
                'quantity' => 100,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Electric Kettle',
                'description' => 'Quick boil electric kettle for the kitchen',
                'price' => 29.99,
                'discount' => 15,
                'quantity' => 150,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Washing Machine',
                'description' => 'High-efficiency washing machine with multiple settings',
                'price' => 499.99,
                'discount' => 20,
                'quantity' => 70,
                'featured' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Portable Charger',
                'description' => 'Compact portable charger for on-the-go charging',
                'price' => 39.99,
                'discount' => 0,
                'quantity' => 500,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'External Hard Drive',
                'description' => 'Portable external hard drive for additional storage',
                'price' => 89.99,
                'discount' => 5,
                'quantity' => 200,
                'featured' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ]
        ]);
    }
}
